name: Lucas Stephanou
description: "notas, idéias e aventuras no desenvolvimento web"
url: http://lucas-ts.com
paginate: 10
permalink: :title.html
exclude: ["vendor"]
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
